import asyncio,sys,os
from pathlib import Path
from pypdf import PdfReader
from playwright.async_api import async_playwright, expect
checks=0
async def check(value,message):
 global checks
 assert value,message
 checks+=1;print('PASS '+message,flush=True)
async def main():
 async with async_playwright() as pw:
  browser=await pw.chromium.launch()
  page=await browser.new_page(viewport={"width":1550,"height":1100})
  page.set_default_timeout(12000)
  errors=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
  async def section(name):
   await page.get_by_role('button',name=name,exact=True).first.click();await page.wait_for_timeout(250)
  try:
   await page.goto(sys.argv[1]+'/demo/counterparts');await page.wait_for_timeout(650)
   if os.environ.get('FLEXCORE_COUNTERPART_ONLY')!='PDF':
    form=page.locator('.fx-form').first
    name=form.get_by_role('textbox',name='Name',exact=True)
    await name.fill('');await name.press_sequentially('Long new name',delay=70)
    await check(await name.input_value()=='Long new name','form accepts continuous typing across renders')
    qty=form.get_by_role('textbox',name='Quantity',exact=True)
    await qty.fill('-');await form.get_by_role('button',name='Save',exact=True).click()
    await expect(page.locator('#demo-status')).to_contain_text('Correct')
    await check(await qty.input_value()=='-' and 'Correct' in await page.locator('#demo-status').inner_text(),'invalid form draft retained and submit rejected')
    await qty.fill('12');await form.get_by_role('button',name='Save',exact=True).click();await page.wait_for_timeout(200)
    await check('quantity 12' in await page.locator('#demo-status').inner_text(),'corrected form draft saves')
    await section('Selection')
    city=page.get_by_role('combobox',name='City',exact=True)
    await city.press_sequentially('Sea',delay=120)
    await page.get_by_role('option',name='Seattle',exact=True).wait_for()
    await city.press('ArrowDown');await city.press('Enter');await page.wait_for_timeout(200)
    await check('Seattle' in await page.locator('#city-value').inner_text(),'autocomplete keyboard suggestion commits')
    await page.get_by_role('radio',name='Express',exact=True).check()
    await check(await page.get_by_role('radio',name='Express',exact=True).is_checked(),'radio group selects item')
    time=page.get_by_role('combobox',name='Appointment time',exact=True)
    await time.fill('1:30 PM');await time.press('Enter');await page.wait_for_timeout(200)
    await check('1:30' in await page.locator('#time-value').inner_text() and 'PM' in await page.locator('#time-value').inner_text(),'time picker commits typed clock value')
    await page.get_by_role('button',name='2. Review',exact=True).click()
    await expect(page.locator('#step-value')).to_have_text('Step: 2')
    await check(await page.locator('#step-value').inner_text()=='Step: 2','stepper navigation updates bound step')
    await page.get_by_role('option',name='#FF0000',exact=True).click()
    await expect(page.locator('#color-value')).to_contain_text('#FF0000')
    await check('#FF0000' in await page.locator('#color-value').inner_text(),'standalone palette updates selected color')
    await page.locator('.fx-calendar').get_by_role('button',name='Sunday, September 6, 2026',exact=True).click()
    await expect(page.locator('#calendar-value')).to_contain_text('9/6/2026')
    await check('9/6/2026' in await page.locator('#calendar-value').inner_text(),'standalone calendar selection binds')
    await section('Charts')
    await check(await page.get_by_role('meter').count()==4 and await page.locator('.fx-gauge svg').count()==4,'all dedicated gauge shapes render')
    await page.get_by_role('button',name='Zoom in',exact=True).click();await page.wait_for_timeout(200)
    await expect(page.locator('#demo-status')).to_contain_text('Stock range')
    await check('Stock range' in await page.locator('#demo-status').inner_text(),'financial navigator publishes zoom range')
    await section('Docking')
    await page.get_by_role('tab',name='Files',exact=True).click()
    await page.get_by_role('button',name='Float',exact=True).click()
    floating=page.get_by_role('dialog',name='Files',exact=True);await floating.wait_for()
    await check(await floating.count()==1,'dock pane floats in existing dialog')
    await floating.get_by_role('button',name='Unpin',exact=True).click();await page.wait_for_timeout(150)
    await page.locator('.fx-dock-auto-hidden').get_by_role('button',name='Files',exact=True).click()
    await page.locator('.fx-dock-drawer').get_by_role('button',name='Pin',exact=True).click()
    await expect(page.get_by_role('tab',name='Files',exact=True)).to_have_count(1)
    await check(await page.get_by_role('tab',name='Files',exact=True).count()==1,'unpinned drawer can be pinned again')
    await page.get_by_role('button',name='Save layout',exact=True).click()
    await page.locator('.fx-dock-actions').get_by_role('button',name='Close',exact=True).click()
    await expect(page.get_by_role('tab',name='Files',exact=True)).to_have_count(0)
    await page.get_by_role('button',name='Restore layout',exact=True).click();await page.wait_for_timeout(200)
    await check(await page.get_by_role('tab',name='Files',exact=True).count()==1,'saved docking state restores closed pane')
    await section('Gantt')
    row=page.locator('.fx-treegrid tbody tr').filter(has_text='Implementation').first
    await row.locator('td').first.dblclick();await page.wait_for_timeout(200)
    editor=page.get_by_role('dialog',name='Edit task',exact=True)
    await editor.get_by_role('textbox',name='Title',exact=True).fill('Implementation revised')
    await editor.get_by_role('button',name='Save task',exact=True).click();await page.wait_for_timeout(250)
    await expect(editor).to_have_count(0)
    await check(await editor.count()==0 and await page.locator('.fx-gantt').get_by_text('Implementation revised',exact=True).count()>0,'Gantt dialog commits task draft')
    end_before=await page.locator('.fx-treegrid tbody tr').filter(has_text='Implementation revised').first.locator('td').nth(2).inner_text()
    bar=page.locator('.fx-gantt-task').filter(has_text='Implementation revised').locator('.fx-gantt-resize.end')
    box=await bar.bounding_box();await page.mouse.move(box['x']+3,box['y']+10);await page.mouse.down();await page.wait_for_timeout(100);await page.mouse.move(box['x']-29,box['y']+10,steps=3);await page.mouse.up();await page.wait_for_timeout(300)
    await expect(page.locator('.fx-treegrid tbody tr').filter(has_text='Implementation revised').first.locator('td').nth(2)).not_to_have_text(end_before)
    await check('Task schedule updated' in await page.locator('#demo-status').inner_text(),'Gantt drag resize commits through schedule callback')
   await section('PDF')
   await page.get_by_text('Page 1 of 2',exact=True).wait_for(timeout=25000)
   await page.locator('.fx-pdf-text span').first.wait_for(timeout=25000)
   await check(await page.locator('.fx-pdf-page canvas').evaluate('(c)=>c.width>500&&c.height>700'),'PDF canvas renders real page')
   await check(await page.locator('.fx-pdf-viewer select,.fx-pdf-viewer input[type=date]').count()==0,'PDF form UI uses FlexCore selectors')
   # Select actual text-layer content, then use the viewer's normal highlight command.
   await page.locator('.fx-pdf-text span').filter(has_text='Select this sentence').evaluate("""span=>{const range=document.createRange();range.selectNodeContents(span);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);}""")
   await page.get_by_role('button',name='Highlight selection',exact=True).click()
   await expect(page.locator('.fx-pdf-sidebar').get_by_role('button').filter(has_text='Highlight — Select this sentence')).to_have_count(1)
   await check(True,'PDF selected text creates highlight annotation')
   await page.locator('.fx-pdf-sidebar').get_by_role('textbox',name='Name',exact=True).fill('Edited customer')
   await page.locator('.fx-pdf-sidebar').get_by_role('textbox',name='Name',exact=True).press('Tab');await page.wait_for_timeout(700)
   await page.get_by_role('button',name='Next page',exact=True).click();await page.get_by_text('Page 2 of 2',exact=True).wait_for()
   await page.get_by_role('button',name='Previous page',exact=True).click();await page.wait_for_timeout(500)
   await page.get_by_role('textbox',name='Search document',exact=True).fill('verification')
   await page.get_by_role('button',name='Find',exact=True).click();await page.wait_for_timeout(400)
   await check(await page.locator('.fx-pdf-sidebar').get_by_role('button').filter(has_text='Page 2:').count()>0,'PDF search finds text on another page')
   await page.get_by_role('button',name='Add note',exact=True).click()
   await page.get_by_role('textbox',name='Note text',exact=True).fill('Review this page')
   await page.get_by_role('dialog',name='Add note',exact=True).get_by_role('button',name='Add note',exact=True).click();await page.wait_for_timeout(600)
   await check(await page.locator('.fx-pdf-sidebar').get_by_role('button').filter(has_text='Review this page').count()==1,'PDF note is present in annotation UI')
   await page.locator('.fx-pdf-sidebar').get_by_role('textbox',name='Name',exact=True).fill('Edited customer final')
   async with page.expect_download() as download_info:
    await page.get_by_role('button',name='Download',exact=True).click()
   download=await download_info.value;await download.save_as('verified-output.pdf')
   reader=PdfReader('verified-output.pdf')
   await check(len(reader.pages)==2 and reader.get_fields()['Name']['/V']=='Edited customer final','independent PDF reader verifies saved form value and pages')
   annotations=[ref.get_object() for pdf_page in reader.pages for ref in pdf_page.get('/Annots',[])]
   await check(any(a.get('/Subtype')=='/Text' and a.get('/Contents')=='Review this page' for a in annotations),'independent PDF reader verifies saved note')
   await check(any(a.get('/Subtype')=='/Highlight' and a.get('/QuadPoints') for a in annotations),'independent PDF reader verifies saved highlight geometry')
   await page.get_by_role('button',name='Save to host',exact=True).click()
   await expect(page.locator('#demo-status')).to_contain_text('PDF bytes to the host')
   await check(True,'PDF SaveAsync streams edited bytes back to the host')
   await page.locator('.fx-pdf-viewer input[type=file]').set_input_files('verified-output.pdf')
   await expect(page.locator('.fx-pdf-sidebar').get_by_role('textbox',name='Name',exact=True)).to_have_value('Edited customer final')
   await check(True,'PDF file picker reopens saved document with edited fields')
   await page.locator('.fx-pdf-viewer input[type=file]').set_input_files({'name':'invalid.pdf','mimeType':'application/pdf','buffer':b'not a PDF document'})
   await expect(page.locator('.fx-pdf-error')).to_contain_text('Invalid PDF')
   await check(await page.locator('.fx-pdf-page canvas').evaluate('(c)=>c.width===0'),'invalid replacement PDF clears previous page and reports error')
   if os.environ.get('FLEXCORE_COUNTERPART_ONLY')!='PDF':
    await section('AI prompt')
    await page.get_by_role('button',name='Generate',exact=True).click();await page.get_by_role('button',name='Use response',exact=True).wait_for()
    await page.get_by_role('button',name='Use response',exact=True).click()
    await expect(page.locator('#demo-status')).to_contain_text('Demo response:')
    await check('Demo response:' in await page.locator('#demo-status').inner_text(),'AI prompt applies provider result')
   await check(not errors,'no browser or Blazor errors: '+str(errors))
   await page.screenshot(path='counterparts-verified.png',full_page=True)
   print(f'All {checks} browser checks passed.',flush=True)
  except:
   print('BROWSER ERRORS',errors,flush=True)
   print((await page.locator('body').inner_text())[-3500:],flush=True)
   await page.screenshot(path='counterparts-failure.png',full_page=True)
   raise
  finally:await browser.close()
asyncio.run(main())
