using Microsoft.AspNetCore.Components;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace Fx.ControlKit.Grid;

public partial class GridControl<TValue>
{
    /// <summary>
    /// Generates columns from the public readable properties of
    /// <typeparamref name="TValue"/>. Disabled by default, so every existing
    /// grid keeps its current explicit/dynamic column behavior.
    /// </summary>
    [Parameter] public bool AutoGenerateColumns { get; set; }

    /// <summary>
    /// Optional one-level parent header bands. A matching entry takes
    /// precedence over <see cref="GridColumn.HeaderBand"/>.
    /// </summary>
    [Parameter] public IReadOnlyList<GridColumnHeaderBand>? ColumnHeaderBands { get; set; }

    private List<GridColumn>? _autoGeneratedColumns;
    private List<string>? _autoGeneratedColumnOrder;

    private IReadOnlyList<GridColumn> GetAutoGeneratedColumns()
    {
        if (_autoGeneratedColumns != null)
            return _autoGeneratedColumns;

        var modelType = Nullable.GetUnderlyingType(typeof(TValue)) ?? typeof(TValue);
        if (IsScalarModelType(modelType))
            return _autoGeneratedColumns = new List<GridColumn>();

        var properties = modelType
            .GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(property => property.GetMethod?.IsPublic == true
                && property.GetIndexParameters().Length == 0)
            .Select((property, declarationOrder) => new
            {
                Property = property,
                DeclarationOrder = declarationOrder,
                Display = property.GetCustomAttribute<DisplayAttribute>(inherit: true)
            })
            .Where(entry => entry.Display?.GetAutoGenerateField() != false
                && entry.Property.GetCustomAttribute<ScaffoldColumnAttribute>(inherit: true)?.Scaffold != false)
            .OrderBy(entry => entry.Display?.GetOrder() ?? int.MaxValue)
            .ThenBy(entry => entry.DeclarationOrder)
            .ToList();

        var result = new List<GridColumn>(properties.Count);
        foreach (var entry in properties)
            result.Add(CreateAutoGeneratedColumn(entry.Property, entry.Display));

        return _autoGeneratedColumns = result;
    }

    private IReadOnlyList<GridColumn> GetEffectiveColumns()
    {
        var explicitColumns = _columnsContainer?.Columns;
        if (!AutoGenerateColumns)
        {
            if (explicitColumns is { Count: > 0 })
                return explicitColumns;

            return AvailableColumns == null
                ? Array.Empty<GridColumn>()
                : AvailableColumns
                    .Where(column => !string.IsNullOrWhiteSpace(column.Field))
                    .Select(CreateTransientColumn)
                    .ToList();
        }

        var generated = GetAutoGeneratedColumns();
        if (explicitColumns is not { Count: > 0 })
            return ApplyAutoGeneratedColumnOrder(generated);
        if (generated.Count == 0)
            return ApplyAutoGeneratedColumnOrder(explicitColumns);

        // An explicitly declared column with the same Field customizes the
        // metadata-generated slot. Extra explicit columns (commands/formulas)
        // follow the generated model properties.
        var explicitByField = explicitColumns
            .Where(column => !string.IsNullOrWhiteSpace(column.Field))
            .GroupBy(column => column.Field, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(group => group.Key, group => group.First(), StringComparer.OrdinalIgnoreCase);
        var used = new HashSet<GridColumn>();
        var merged = new List<GridColumn>(generated.Count + explicitColumns.Count);
        foreach (var generatedColumn in generated)
        {
            if (explicitByField.TryGetValue(generatedColumn.Field, out var configured))
            {
                merged.Add(configured);
                used.Add(configured);
            }
            else
            {
                merged.Add(generatedColumn);
            }
        }

        foreach (var configured in explicitColumns)
            if (!used.Contains(configured))
                merged.Add(configured);

        return ApplyAutoGeneratedColumnOrder(merged);
    }

    /// <summary>
    /// Applies a field order to the active column source. The metadata path
    /// stores an instance-local ordering overlay because generated columns do
    /// not have a declarative <see cref="GridColumnsBase"/> to mutate.
    /// </summary>
    private bool ApplyEffectiveColumnOrder(IEnumerable<string> fieldsInOrder)
    {
        if (!AutoGenerateColumns)
            return _columnsContainer?.ReorderColumns(fieldsInOrder) == true;

        var columns = GetEffectiveColumns();
        if (columns.Count == 0)
            return false;

        var liveByField = columns
            .Where(column => !string.IsNullOrWhiteSpace(column.Field))
            .GroupBy(column => column.Field, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(group => group.Key, group => group.First(), StringComparer.OrdinalIgnoreCase);
        var normalized = new List<string>(columns.Count);
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var field in fieldsInOrder)
            if (!string.IsNullOrWhiteSpace(field) && liveByField.ContainsKey(field) && seen.Add(field))
                normalized.Add(liveByField[field].Field);
        foreach (var column in columns)
            if (!string.IsNullOrWhiteSpace(column.Field) && seen.Add(column.Field))
                normalized.Add(column.Field);

        var current = columns
            .Where(column => !string.IsNullOrWhiteSpace(column.Field))
            .Select(column => column.Field)
            .ToList();
        if (current.SequenceEqual(normalized, StringComparer.OrdinalIgnoreCase))
            return false;

        _autoGeneratedColumnOrder = normalized;
        return true;
    }

    private bool ReorderEffectiveColumn(string fromField, string toField, bool insertAfter)
    {
        if (!AutoGenerateColumns)
            return _columnsContainer?.ReorderColumn(fromField, toField, insertAfter) == true;

        var order = GetEffectiveColumns()
            .Where(column => !string.IsNullOrWhiteSpace(column.Field))
            .Select(column => column.Field)
            .ToList();
        var fromIndex = order.FindIndex(field =>
            string.Equals(field, fromField, StringComparison.OrdinalIgnoreCase));
        var toIndex = order.FindIndex(field =>
            string.Equals(field, toField, StringComparison.OrdinalIgnoreCase));
        if (fromIndex < 0 || toIndex < 0 || fromIndex == toIndex)
            return false;

        var moving = order[fromIndex];
        order.RemoveAt(fromIndex);
        if (fromIndex < toIndex)
            toIndex--;
        order.Insert(Math.Clamp(insertAfter ? toIndex + 1 : toIndex, 0, order.Count), moving);
        return ApplyEffectiveColumnOrder(order);
    }

    private IReadOnlyList<GridColumn> ApplyAutoGeneratedColumnOrder(IReadOnlyList<GridColumn> columns)
    {
        if (_autoGeneratedColumnOrder is not { Count: > 0 } || columns.Count < 2)
            return columns;

        var byField = columns
            .Where(column => !string.IsNullOrWhiteSpace(column.Field))
            .GroupBy(column => column.Field, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(group => group.Key, group => group.First(), StringComparer.OrdinalIgnoreCase);
        var ordered = new List<GridColumn>(columns.Count);
        var seen = new HashSet<GridColumn>();
        foreach (var field in _autoGeneratedColumnOrder)
        {
            if (byField.TryGetValue(field, out var column) && seen.Add(column))
                ordered.Add(column);
        }
        foreach (var column in columns)
            if (seen.Add(column))
                ordered.Add(column);
        return ordered;
    }

    #pragma warning disable BL0005 // Runtime metadata creates non-rendered GridColumn descriptors.
    private static GridColumn CreateAutoGeneratedColumn(PropertyInfo property, DisplayAttribute? display)
    {
        var propertyType = Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;
        var columnType = ResolveAutoGeneratedColumnType(property, propertyType);
        var isKey = property.IsDefined(typeof(KeyAttribute), inherit: true);
        var editable = property.GetCustomAttribute<EditableAttribute>(inherit: true);
        var readOnly = property.GetCustomAttribute<ReadOnlyAttribute>(inherit: true);
        var displayFormat = property.GetCustomAttribute<DisplayFormatAttribute>(inherit: true);
        var displayName = property.GetCustomAttribute<DisplayNameAttribute>(inherit: true);
        var canWrite = property.SetMethod?.IsPublic == true;

        return new GridColumn
        {
            Field = property.Name,
            HeaderText = display?.GetName() ?? displayName?.DisplayName ?? property.Name,
            HeaderBand = display?.GetGroupName(),
            Type = columnType,
            Format = ExtractDotNetFormat(displayFormat?.DataFormatString),
            IsPrimaryKey = isKey,
            AllowEditing = canWrite && !isKey && editable?.AllowEdit != false && readOnly?.IsReadOnly != true,
            TextAlign = columnType switch
            {
                ColumnType.Number or ColumnType.Date => TextAlign.Right,
                ColumnType.Boolean or ColumnType.CheckBox => TextAlign.Center,
                _ => TextAlign.Left
            },
            HeaderTextAlign = columnType switch
            {
                ColumnType.Number or ColumnType.Date => TextAlign.Right,
                ColumnType.Boolean or ColumnType.CheckBox => TextAlign.Center,
                _ => TextAlign.Left
            }
        };
    }
    #pragma warning restore BL0005

    private static ColumnType ResolveAutoGeneratedColumnType(PropertyInfo property, Type propertyType)
    {
        var dataType = property.GetCustomAttribute<DataTypeAttribute>(inherit: true)?.DataType;
        if (dataType == DataType.Password)
            return ColumnType.Password;
        if (dataType is DataType.Date or DataType.DateTime or DataType.Time)
            return ColumnType.Date;
        if (propertyType == typeof(bool))
            return ColumnType.CheckBox;
        if (propertyType == typeof(DateTime)
            || propertyType == typeof(DateTimeOffset)
            || propertyType == typeof(DateOnly))
        {
            return ColumnType.Date;
        }

        if (propertyType == typeof(byte) || propertyType == typeof(sbyte)
            || propertyType == typeof(short) || propertyType == typeof(ushort)
            || propertyType == typeof(int) || propertyType == typeof(uint)
            || propertyType == typeof(long) || propertyType == typeof(ulong)
            || propertyType == typeof(float) || propertyType == typeof(double)
            || propertyType == typeof(decimal))
        {
            return ColumnType.Number;
        }

        return ColumnType.Text;
    }

    private static string? ExtractDotNetFormat(string? compositeFormat)
    {
        if (string.IsNullOrWhiteSpace(compositeFormat))
            return null;

        var format = compositeFormat.Trim();
        if (format.StartsWith("{0:", StringComparison.Ordinal)
            && format.EndsWith('}')
            && format.Length > 4)
        {
            return format[3..^1];
        }

        return format.Equals("{0}", StringComparison.Ordinal) ? null : format;
    }

    private static bool IsScalarModelType(Type modelType)
        => modelType.IsPrimitive
            || modelType.IsEnum
            || modelType == typeof(string)
            || modelType == typeof(decimal)
            || modelType == typeof(DateTime)
            || modelType == typeof(DateTimeOffset)
            || modelType == typeof(DateOnly)
            || modelType == typeof(TimeOnly)
            || modelType == typeof(Guid);

    private void UpdateFrozenColumnOffsets()
    {
        var allColumns = GetEffectiveColumns();
        if (!allColumns.Any(column => column.EffectiveIsFrozen))
            return;

        foreach (var column in allColumns.Where(column => column.EffectiveIsFrozen))
            column.FrozenOffsetCss = null;

        // VisibleColumns also excludes grouped columns when
        // HideGroupedColumns is active; hidden/group-placeholder fields must
        // not leave a phantom gap in the sticky stack.
        var visible = VisibleColumns.ToList();
        var precedingWidths = new List<string>();
        foreach (var column in visible)
        {
            if (!column.EffectiveIsFrozen || column.EffectiveFrozenPosition != FrozenColumnPosition.Left)
                continue;

            column.FrozenOffsetCss = BuildCssLengthSum(precedingWidths);
            precedingWidths.Add(column.GetEffectiveWidthCss());
        }

        precedingWidths.Clear();
        for (var index = visible.Count - 1; index >= 0; index--)
        {
            var column = visible[index];
            if (!column.EffectiveIsFrozen || column.EffectiveFrozenPosition != FrozenColumnPosition.Right)
                continue;

            column.FrozenOffsetCss = BuildCssLengthSum(precedingWidths);
            precedingWidths.Add(column.GetEffectiveWidthCss());
        }
    }

    private static string BuildCssLengthSum(IReadOnlyList<string> terms)
        => terms.Count switch
        {
            0 => "0px",
            1 => terms[0],
            _ => $"calc({string.Join(" + ", terms)})"
        };

    private bool HasColumnHeaderBandConfiguration()
        => ColumnHeaderBands is { Count: > 0 }
            || GetRenderVisibleColumns().Any(column => !string.IsNullOrWhiteSpace(column.HeaderBand));

    private IReadOnlyList<ColumnHeaderBandRun> GetColumnHeaderBandRuns()
    {
        var visible = GetRenderVisibleColumns();
        if (visible.Count == 0)
            return Array.Empty<ColumnHeaderBandRun>();

        var configuredByField = new Dictionary<string, ResolvedColumnHeaderBand>(StringComparer.OrdinalIgnoreCase);
        if (ColumnHeaderBands is { Count: > 0 })
        {
            for (var bandIndex = 0; bandIndex < ColumnHeaderBands.Count; bandIndex++)
            {
                var band = ColumnHeaderBands[bandIndex];
                if (band?.Fields == null)
                    continue;

                var resolved = new ResolvedColumnHeaderBand($"configured:{bandIndex}", band);
                foreach (var field in band.Fields)
                {
                    if (!string.IsNullOrWhiteSpace(field))
                        configuredByField.TryAdd(field, resolved);
                }
            }
        }

        var runs = new List<ColumnHeaderBandRun>();
        foreach (var column in visible)
        {
            ResolvedColumnHeaderBand? resolved = null;
            if (!configuredByField.TryGetValue(column.Field, out resolved)
                && !string.IsNullOrWhiteSpace(column.HeaderBand))
            {
                resolved = new ResolvedColumnHeaderBand(
                    $"column:{column.HeaderBand}",
                    new GridColumnHeaderBand { HeaderText = column.HeaderBand! });
            }

            var bandIdentity = resolved?.Identity ?? $"unbanded:{column.Field}";
            // A spanning cell cannot be partly sticky. Split a logical band at
            // frozen/non-frozen boundaries and repeat its caption, just as we
            // split it when reordering makes its fields non-contiguous.
            var positioningIdentity = column.EffectiveIsFrozen
                ? $"frozen:{column.EffectiveFrozenPosition}"
                : "scrolling";
            var runIdentity = $"{bandIdentity}|{positioningIdentity}";
            if (runs.Count > 0 && string.Equals(runs[^1].Identity, runIdentity, StringComparison.Ordinal))
            {
                runs[^1].Columns.Add(column);
            }
            else
            {
                runs.Add(new ColumnHeaderBandRun(runIdentity, resolved?.Band, column));
            }
        }

        return runs;
    }

    private string GetColumnHeaderBandStyle(ColumnHeaderBandRun run)
    {
        var widths = run.Columns.Select(column => column.GetEffectiveWidthCss()).ToList();
        var totalWidth = BuildCssLengthSum(widths);
        var align = run.Band?.TextAlign.ToString().ToLowerInvariant() ?? "center";
        var style = $"width:{totalWidth};text-align:{align};";

        var first = run.Columns[0];
        var allFrozenTogether = first.EffectiveIsFrozen
            && run.Columns.All(column => column.EffectiveIsFrozen && column.EffectiveFrozenPosition == first.EffectiveFrozenPosition);
        if (!allFrozenTogether)
            return style;

        var edgeColumn = first.EffectiveFrozenPosition == FrozenColumnPosition.Right
            ? run.Columns[^1]
            : first;
        var offset = string.IsNullOrWhiteSpace(edgeColumn.FrozenOffsetCss)
            ? "0px"
            : edgeColumn.FrozenOffsetCss;
        var side = first.EffectiveFrozenPosition == FrozenColumnPosition.Right ? "right" : "left";
        return $"{style}position:sticky;{side}:{offset};z-index:4;background:var(--fx-grid-header-bg,#fff);";
    }

    private sealed record ResolvedColumnHeaderBand(string Identity, GridColumnHeaderBand Band);

    private sealed class ColumnHeaderBandRun
    {
        public ColumnHeaderBandRun(string identity, GridColumnHeaderBand? band, GridColumn firstColumn)
        {
            Identity = identity;
            Band = band;
            Columns.Add(firstColumn);
        }

        public string Identity { get; }
        public GridColumnHeaderBand? Band { get; }
        public List<GridColumn> Columns { get; } = new();
    }
}
