from playwright.async_api import expect
async def run_operations(page, base, passed):
    async def button(name): await page.get_by_role('button', name=name, exact=True).click()
    async def dropdown(name,value):
        await page.get_by_role('button',name=name,exact=True).click()
        await page.get_by_role('option',name=value,exact=True).click()
    def row(id): return page.locator(f'.fx-treegrid-body tr[data-node-id="{id}"]')
    def cell(id,field): return row(id).locator(f'td[data-tree-field="{field}"]')
    source=page.locator('#operations-source')
    await page.goto(base+'/flexcore-controls/tree-grid-operations')
    await expect(page.locator('#operations-ready')).to_have_attribute('data-ready','true')
    await expect(row(1)).to_be_visible()
    viewport=page.locator('.fx-treegrid-content')
    left=await cell(1,'Name').bounding_box(); right=await cell(1,'Active').bounding_box()
    await viewport.evaluate('(el)=>el.scrollLeft=450'); await page.wait_for_timeout(120)
    left2=await cell(1,'Name').bounding_box(); right2=await cell(1,'Active').bounding_box()
    assert abs(left['x']-left2['x'])<2 and abs(right['x']-right2['x'])<2, (left,left2,right,right2)
    assert abs((await page.locator('th[data-tree-field="Name"]').bounding_box())['x']-left2['x'])<2
    passed('Frozen columns pin both edges and align headers during horizontal scroll')
    await viewport.evaluate('(el)=>el.scrollLeft=0')
    await row(1).get_by_role('checkbox').check()
    await expect(page.locator('#operations-checks')).to_have_text('Checked: 1,11,111,12')
    await cell(1,'Name').click(); await page.keyboard.press('ArrowRight')
    await row(11).get_by_role('checkbox').uncheck()
    await expect(row(1).get_by_role('checkbox')).to_have_attribute('aria-checked','mixed')
    await expect(row(14).get_by_role('checkbox')).to_be_disabled()
    await button('Find Draft'); await expect(page.locator('#operations-checks')).to_have_text('Checked: 12')
    await button('Clear filters')
    passed('Hierarchy checks cascade, compute mixed state and survive filtering')
    await page.get_by_role('checkbox',name='Fail next child load',exact=True).check()
    await row(900).get_by_role('checkbox').check(); await cell(900,'Name').click(); await page.keyboard.press('ArrowRight')
    await expect(page.get_by_text('Simulated child load failure. Expand Remote to retry.',exact=True)).to_be_visible()
    await page.keyboard.press('ArrowRight')
    await expect(row(901).get_by_role('checkbox')).to_be_checked()
    await expect(page.locator('#operations-ready')).to_contain_text('Lazy requests: 2')
    passed('Checked remote parents inherit checks after a failed load and retry')
    await button('Expand all'); await cell(11,'Name').dblclick()
    name=row(11).get_by_role('textbox',name='Name',exact=True)
    await name.fill(''); await name.press_sequentially('Revised specification',delay=20)
    await expect(name).to_have_value('Revised specification')
    await expect(source).to_contain_text('11:1:Draft specification:20')
    amount=row(11).get_by_role('textbox',name='Budget',exact=True)
    await amount.fill('invalid'); await button('Save row')
    await expect(amount).to_have_value('invalid'); await expect(row(11)).to_contain_text('Enter a valid Budget.')
    await cell(12,'Name').click(); await expect(amount).to_be_visible()
    await amount.fill('0'); await button('Save row'); await expect(source).to_contain_text('11:1:Draft specification:20')
    await amount.fill('20000'); await button('Save row')
    await expect(page.get_by_text('Budget must not exceed 10,000.',exact=True).first).to_be_visible()
    await amount.fill('42'); await name.press('Enter')
    await expect(source).to_contain_text('11:1:Revised specification:42'); await expect(name).to_have_count(0)
    passed('Inline editors preserve keystrokes, parsing errors and annotations before Enter commits')
    await cell(12,'Name').click(); await page.keyboard.press('F2')
    edit=row(12).get_by_role('textbox',name='Name',exact=True)
    await edit.fill('Discarded value'); await edit.press('Escape')
    await expect(source).to_contain_text('12:1:Build prototype:30')
    passed('F2 opens editing and Escape discards the row draft')
    await dropdown('Editing mode','Batch'); await cell(12,'Name').dblclick()
    await row(12).get_by_role('textbox',name='Name',exact=True).press('Tab')
    await expect(row(12).get_by_role('textbox',name='Team',exact=True)).to_be_focused()
    await row(12).get_by_role('textbox',name='Team',exact=True).press('Shift+Tab')
    await expect(row(12).get_by_role('textbox',name='Name',exact=True)).to_be_focused()
    await button('Cancel changes')
    passed('Batch Tab and Shift+Tab move between editable fields and skip the ID column')
    await dropdown('Editing mode','Dialog'); await cell(12,'Name').dblclick()
    dialog=page.get_by_role('dialog',name='Edit tree row'); name=dialog.get_by_role('textbox',name='Name',exact=True)
    await name.fill(''); await name.press_sequentially('Dialog task',delay=20); await expect(name).to_have_value('Dialog task')
    await expect(source).to_contain_text('12:1:Build prototype:30')
    assert await dialog.locator('select,input[type=date],input[type=number]').count()==0
    await name.press('Enter'); await expect(dialog).not_to_be_visible(); await expect(source).to_contain_text('12:1:Dialog task:30')
    passed('Dialog editing uses FlexCore editors and commits a complete typed draft')
    await dropdown('Editing mode','Batch'); await cell(11,'Name').dblclick()
    edit=row(11).get_by_role('textbox',name='Name',exact=True)
    await edit.fill('Batch first'); await edit.press('Enter')
    await expect(cell(11,'Name')).to_contain_text('Batch first'); await expect(source).to_contain_text('11:1:Revised specification:42')
    await cell(12,'Budget').dblclick()
    edit=row(12).get_by_role('textbox',name='Budget',exact=True)
    await edit.fill('55'); await edit.press('Enter'); await expect(source).to_contain_text('12:1:Dialog task:30')
    await page.get_by_role('checkbox',name='Reject next change',exact=True).check(); await button('Save changes')
    await expect(page.get_by_text('Simulated server rejection. Drafts are retained.',exact=True)).to_be_visible()
    await expect(source).to_contain_text('11:1:Revised specification:42')
    await button('Save changes'); await expect(source).to_contain_text('11:1:Batch first:42'); await expect(source).to_contain_text('12:1:Dialog task:55')
    passed('Batch Enter stages multiple rows; server veto retains drafts and Save commits atomically')
    await page.get_by_role('checkbox',name='Check all loaded rows',exact=True).check()
    await page.get_by_role('checkbox',name='Check all loaded rows',exact=True).uncheck()
    await expect(page.locator('#operations-checks')).to_have_text('Checked:')
    await cell(11,'Name').click(); await button('Delete'); await button('Delete rows')
    await expect(row(11)).to_have_count(0); await expect(row(111)).to_have_count(0); await expect(source).to_contain_text('111:11:Review draft:5')
    await button('Cancel changes'); await expect(row(11)).to_be_visible(); await expect(row(111)).to_be_visible()
    passed('Batch subtree delete and Cancel preserve the original records')
    await cell(2,'Name').click(); await button('Add child')
    await page.get_by_role('dialog',name='Add tree row').get_by_role('textbox',name='Name',exact=True).fill('Added under Sales')
    await button('Stage row'); await button('Save changes'); await expect(source).to_contain_text('1000:2:Added under Sales:1')
    passed('Add child drafts receive unique IDs and the selected parent')
    await cell(1,'Name').click(); await button('Move row…'); await dropdown('Destination row','Review draft'); await button('Move')
    await expect(page.get_by_role('dialog',name='Move tree row')).to_be_visible(); await expect(source).to_contain_text('1:root:Engineering:100')
    await page.get_by_role('dialog',name='Move tree row').get_by_role('button',name='Cancel',exact=True).click()
    await cell(11,'Name').click(); await button('Move row…'); await dropdown('Destination row','Sales'); await button('Move')
    await expect(source).to_contain_text('11:2:Batch first:42'); await expect(source).to_contain_text('111:11:Review draft:5')
    await expect(row(111)).to_have_attribute('aria-level','3')
    await cell(11,'Name').click(); await button('Outdent'); await expect(source).to_contain_text('11:root:Batch first:42')
    await button('Indent'); await expect(source).to_contain_text('11:2:Batch first:42')
    passed('Move dialog rejects cycles, preserves subtrees, and supports indent/outdent')
    await cell(12,'Name').scroll_into_view_if_needed()
    start=await cell(12,'Name').bounding_box()
    await page.mouse.move(start['x']+100,start['y']+start['height']/2); await page.mouse.down()
    await page.mouse.move(start['x']+130,start['y']+start['height']/2+10,steps=5)
    drop=row(2).locator('[data-drop-position="Inside"]'); await expect(drop).to_be_visible()
    target=await drop.bounding_box()
    await page.mouse.move(target['x']+target['width']/2,target['y']+target['height']/2,steps=10)
    await page.mouse.up()
    await expect(source).to_contain_text('12:2:Dialog task:55')
    passed('Drag drop uses the same guarded reparent transaction')
    await page.locator('th[data-tree-field="Team"]').click(button='right'); await page.get_by_role('menuitem',name='Freeze left',exact=True).click()
    await expect(page.locator('th[data-tree-field="Team"]')).to_have_attribute('data-tree-frozen','left')
    await viewport.evaluate('(el)=>el.scrollLeft=450'); await page.wait_for_timeout(120)
    namebox=await cell(1,'Name').bounding_box(); teambox=await cell(1,'Team').bounding_box()
    assert abs(teambox['x']-(namebox['x']+namebox['width']))<2, (namebox,teambox)
    # Resize a frozen column, hide its frozen neighbor, then restore visibility.
    await viewport.evaluate('(el)=>el.scrollLeft=0')
    handle=page.locator('th[data-tree-field="Name"] .fx-treegrid-resize-handle')
    edge=await handle.bounding_box()
    await page.mouse.move(edge['x']+edge['width']/2,edge['y']+edge['height']/2); await page.mouse.down()
    await page.mouse.move(edge['x']+70,edge['y']+edge['height']/2,steps=8); await page.mouse.up()
    await page.wait_for_timeout(120)
    namebox=await cell(1,'Name').bounding_box(); teambox=await cell(1,'Team').bounding_box()
    assert abs(teambox['x']-(namebox['x']+namebox['width']))<2
    await button('Columns')
    await page.locator('.fx-treegrid-column-panel').get_by_role('checkbox',name='Name',exact=True).uncheck()
    await expect(page.locator('th[data-tree-field="Name"]')).to_have_count(0)
    await page.wait_for_timeout(120)
    check=await row(1).locator('.fx-treegrid-check-cell').bounding_box(); team=await cell(1,'Team').bounding_box()
    first=await cell(1,'Id').bounding_box()
    assert abs(first['x']-(check['x']+check['width']))<2 and abs(team['x']-(first['x']+first['width']))<2, (check,first,team)
    await page.locator('.fx-treegrid-column-panel').get_by_role('checkbox',name='Name',exact=True).check(); await button('Columns')
    passed('Frozen offsets respond to resized and hidden neighboring columns')
    await button('Save view')
    await page.locator('th[data-tree-field="Team"]').click(button='right'); await page.get_by_role('menuitem',name='Unfreeze column',exact=True).click()
    await button('Restore view'); await expect(page.locator('th[data-tree-field="Team"]')).to_have_attribute('data-tree-frozen','left')
    passed('Header context pinning computes multiple frozen offsets and persists view state')
    assert await page.locator('select,input[type=date]').count()==0
    await page.screenshot(path='/tmp/flexcore-tree-operations.png',full_page=True)
