import asyncio, os, sys, csv, re
from pathlib import Path
from playwright.async_api import async_playwright, expect
from pypdf import PdfReader
import openpyxl

async def main():
    engine = os.environ.get('FLEXCORE_BROWSER', 'chromium')
    checks, errors = [], []
    async with async_playwright() as p:
        browser = await getattr(p, engine).launch()
        page = await browser.new_page(viewport={'width': 1440, 'height': 1000}, accept_downloads=True)
        page.set_default_timeout(10000)
        page.on('pageerror', lambda e: errors.append(str(e)))
        page.on('console', lambda m: errors.append(m.text) if m.type == 'error' else None)
        def passed(name): checks.append(name); print('PASS ' + name, flush=True)
        async def button(name): await page.get_by_role('button', name=name, exact=True).click()
        def node(id): return page.locator(f'[role=treeitem][data-node-id="{id}"]')
        async def dropdown(name, value):
            await page.get_by_role('button', name=name, exact=True).click()
            await page.get_by_role('option', name=value, exact=True).click()
        async def check_selected(ids):
            await expect(page.locator('#tree-selection')).to_have_text('Selected: ' + ','.join(ids))
            actual = await page.locator('[role=treeitem][aria-selected=true]').evaluate_all('(rows)=>rows.map(r=>r.dataset.nodeId)')
            assert actual == ids, actual
        async def check_grid_ids(ids):
            await page.wait_for_function('(ids)=>JSON.stringify([...document.querySelectorAll(".fx-treegrid-body [data-node-id]")].map(r=>r.dataset.nodeId))===JSON.stringify(ids)', arg=ids)
        try:
            if os.environ.get('FLEXCORE_OPERATIONS_ONLY'):
                from operations import run_operations
                await run_operations(page, sys.argv[1], passed)
                assert not errors, errors
                print(f'All {len(checks)} operations browser checks passed ({engine}).', flush=True)
                return
            await page.goto(sys.argv[1] + '/flexcore-controls/tree-view')
            await expect(page.locator('#tree-selection')).to_have_attribute('data-ready', 'true')
            await expect(node('alpha')).to_be_visible()
            await expect(node('literal')).to_have_text('<b>Literal label</b>')
            assert await node('literal').locator('b').count() == 0
            await expect(node('alpha')).to_have_attribute('aria-level', '2')
            passed('TreeView encodes labels and exposes hierarchy semantics')
            await node('alpha').click(); await check_selected(['alpha'])
            await node('beta').click(modifiers=['Meta']); await check_selected(['alpha', 'beta'])
            await node('beta').click(modifiers=['Meta']); await check_selected(['alpha'])
            await expect(node('beta')).not_to_have_class(re.compile('.*fx-treeview-node-selected.*'))
            await node('west').click(modifiers=['Shift']); await check_selected(['beta', 'sales', 'east', 'west'])
            await node('east').click(); await check_selected(['east'])
            await expect(node('disabled')).to_be_disabled(); await node('disabled').click(force=True); await check_selected(['east'])
            passed('Ctrl toggle, Shift range, plain click replacement and disabled selection')
            tree = page.get_by_role('tree', name='Project tree')
            await tree.focus(); await tree.press('Home'); await check_selected(['engineering'])
            await tree.press('ArrowDown'); await check_selected(['alpha'])
            await tree.press('Shift+ArrowDown'); await check_selected(['alpha', 'beta'])
            await tree.press('ArrowDown'); await check_selected(['sales'])
            await tree.press('Control+ArrowDown'); await check_selected(['sales'])
            await expect(tree).to_have_attribute('aria-activedescendant', re.compile('65617374$', re.I))
            passed('Keyboard navigation and range selection skip disabled nodes and separate focus')
            await node('alpha').get_by_role('checkbox').check()
            await expect(node('engineering')).to_have_attribute('aria-checked', 'mixed')
            await node('engineering').get_by_role('checkbox').check()
            await expect(node('beta')).to_have_attribute('aria-checked', 'true')
            await expect(node('engineering')).to_have_attribute('aria-checked', 'true')
            await expect(node('disabled')).to_have_attribute('aria-checked', 'false')
            await node('beta').get_by_role('checkbox').uncheck()
            await expect(node('engineering')).to_have_attribute('aria-checked', 'mixed')
            passed('Cascade checks compute mixed parents and preserve disabled children')
            await page.get_by_role('checkbox', name='Fail next lazy load').check()
            await node('remote').get_by_role('checkbox').check()
            await node('remote').get_by_role('button', name='Expand Remote', exact=True).click()
            await expect(page.locator('#bench-status')).to_contain_text('Simulated load failure')
            await node('remote').get_by_role('button', name='Expand Remote', exact=True).click()
            await expect(node('remote-a')).to_be_visible()
            await expect(node('remote-a')).to_have_attribute('aria-checked', 'true')
            await expect(node('remote-b')).to_have_attribute('aria-checked', 'true')
            await node('remote').get_by_role('button', name='Collapse Remote', exact=True).click()
            await node('remote').get_by_role('button', name='Expand Remote', exact=True).click()
            await expect(page.locator('#tree-loads')).to_have_text('Lazy requests: 2')
            passed('Lazy loading retries errors, caches success and inherits a checked parent')
            await node('alpha').click(); await tree.press('F2')
            edit = page.get_by_role('textbox', name='Rename node')
            await edit.fill('reserved'); await edit.press('Enter')
            await expect(page.locator('#bench-status')).to_have_text('This name is reserved.')
            await expect(edit).to_have_value('reserved')
            await edit.fill('A longer renamed task'); await edit.press('Enter')
            await expect(node('alpha')).to_have_attribute('aria-label', 'A longer renamed task')
            await expect(page.locator('#bench-status')).to_have_text('Renamed: A longer renamed task')
            await tree.press('F2'); await edit.fill('discard'); await edit.press('Escape')
            await expect(node('alpha')).to_have_attribute('aria-label', 'A longer renamed task')
            passed('F2 editing retains keystrokes, validates, commits Enter and cancels Escape')
            await button('Move selected into Sales')
            await expect(page.locator('#bench-status')).to_have_text('Moved A longer renamed task Inside Sales')
            await expect(node('alpha')).to_have_attribute('aria-level', '2')
            await node('sales').get_by_role('button', name='Collapse Sales', exact=True).click()
            await expect(node('alpha')).to_have_count(0)
            await node('sales').get_by_role('button', name='Expand Sales', exact=True).click()
            await button('Move selected before Sales')
            await expect(node('alpha')).to_have_attribute('aria-level', '1')
            await node('beta').drag_to(node('sales'))
            await expect(page.locator('#bench-status')).to_have_text('Moved Beta Inside Sales')
            passed('Sibling moves and native drag/drop reparent intact nodes')
            await button('Save view state'); await button('Collapse all')
            await page.get_by_role('textbox', name='Find a node').fill('West')
            await expect(node('west')).to_be_visible(); await expect(node('sales')).to_be_visible()
            await expect(page.locator('[role=treeitem]')).to_have_count(2)
            await page.get_by_role('textbox', name='Find a node').fill('')
            await expect(node('west')).to_have_count(0)
            await button('Restore view state'); await expect(node('west')).to_be_visible()
            await button('Add to Engineering'); await expect(node('added-1')).to_be_visible()
            await node('added-1').click(); await button('Delete selected subtree'); await expect(node('added-1')).to_have_count(0)
            passed('Filter reveals collapsed matches; state, add/remove update immediately')
            await button('Load 10,000 nodes')
            await expect(node('n1')).to_be_visible()
            assert await page.locator('[role=treeitem]').count() < 60
            await tree.focus(); await tree.press('End'); await expect(node('n10000')).to_be_visible()
            await expect(node('n10000')).to_have_attribute('aria-selected', 'true')
            await tree.press('Home'); await expect(node('n1')).to_be_visible()
            assert await page.locator('[role=treeitem]').count() < 60
            passed('Virtualized 10,000-node tree bounds DOM and scrolls keyboard Home/End into view')
            await page.goto(sys.argv[1] + '/flexcore-controls/tree-grid')
            await expect(page.locator('#tree-grid-sorts')).to_have_attribute('data-ready', 'true')
            await expect(page.get_by_role('treegrid', name='Project plan')).to_be_visible()
            await check_grid_ids(['1', '2', '900'])
            await button('Find Task via API')
            await expect(page.locator('.fx-treegrid-pager')).to_contain_text('8 rows')
            await check_grid_ids(['1', '11', '12', '13', '14'])
            await button('Budget greater than 10')
            await expect(page.locator('.fx-treegrid-pager')).to_contain_text('6 rows')
            await check_grid_ids(['1', '11', '13', '14', '2'])
            await dropdown('Filter relatives', 'None')
            await expect(page.locator('.fx-treegrid-pager')).to_contain_text('4 rows')
            await check_grid_ids(['11', '13', '14', '22'])
            await dropdown('Filter relatives', 'Child')
            await check_grid_ids(['11', '13', '14', '22'])
            await dropdown('Filter relatives', 'Parent')
            await expect(page.locator('.fx-treegrid-pager')).to_contain_text('6 rows')
            passed('Typed numeric filters combine across columns and reveal collapsed matches')
            await button('Clear filters'); await button('Expand all')
            await expect(page.locator('#tree-grid-loads')).to_have_text('Lazy requests: 1')
            await expect(page.locator('.fx-treegrid-pager')).to_contain_text('11 rows')
            await button('Sort Team then Budget')
            await expect(page.locator('#tree-grid-sorts')).to_have_text('Sorts: Team Ascending, Budget Descending')
            await check_grid_ids(['1', '11', '14', '12', '13'])
            await button('Next page'); await check_grid_ids(['2', '22', '21', '900', '901'])
            await button('Previous page')
            await page.locator('.fx-treegrid-body [data-node-id="13"]').click()
            await page.keyboard.press('ArrowDown')
            await expect(page.locator('.fx-treegrid-body [data-node-id="2"]')).to_have_attribute('aria-selected', 'true')
            await expect(page.locator('.fx-treegrid-pager')).to_contain_text('Page 2 of 3')
            await page.keyboard.press('ArrowUp')
            await expect(page.locator('.fx-treegrid-body [data-node-id="13"]')).to_have_attribute('aria-selected', 'true')
            await expect(page.locator('.fx-treegrid-pager')).to_contain_text('Page 1 of 3')
            passed('TreeGrid keyboard navigation crosses page boundaries in both directions')
            await page.get_by_role('columnheader', name='Name', exact=False).first.click(button='right')
            await page.get_by_role('menuitem', name='Custom sort…', exact=True).click()
            dialog = page.get_by_role('dialog', name='Sort tree rows')
            await expect(dialog.get_by_role('button', name='Sort column')).to_have_count(2)
            await dialog.get_by_role('button', name='Up', exact=True).nth(1).click()
            await dialog.get_by_role('button', name='Apply sort', exact=True).click()
            await expect(page.locator('#tree-grid-sorts')).to_have_text('Sorts: Budget Descending, Team Ascending')
            passed('Stable sibling sorting, paging and context-menu sort priorities')
            await button('Save view state'); await button('Collapse all'); await button('Find Task via API')
            await button('Restore view state')
            await expect(page.locator('#bench-status')).to_have_text('View state restored')
            await expect(page.locator('.fx-treegrid-pager')).to_contain_text('11 rows')
            await check_grid_ids(['1', '11', '14', '13', '12'])
            passed('JSON view state restores sorts, filters, expansion and page')
            await button('Clear filters')
            await page.get_by_role('button', name='Filter Budget', exact=True).click()
            await dropdown('Filter operator', 'GreaterThan')
            await page.get_by_role('textbox', name='Filter value', exact=True).fill('10')
            await dropdown('Second operator', 'LessThan')
            await page.get_by_role('textbox', name='Second value', exact=True).fill('30')
            await button('Apply'); await dropdown('Filter relatives', 'None')
            await expect(page.locator('.fx-treegrid-pager')).to_contain_text('3 rows')
            await check_grid_ids(['11', '14', '13'])
            await page.get_by_role('button', name='Filter Budget', exact=True).click()
            await dropdown('Combine conditions', 'Or'); await dropdown('Filter operator', 'Equals')
            await page.get_by_role('textbox', name='Filter value', exact=True).fill('3')
            await dropdown('Second operator', 'Equals')
            await page.get_by_role('textbox', name='Second value', exact=True).fill('100')
            await button('Apply')
            await expect(page.locator('.fx-treegrid-pager')).to_contain_text('2 rows')
            await check_grid_ids(['12', '22'])
            assert await page.locator('select').count() == 0
            passed('FlexCore filter dropdowns apply numeric AND/OR conditions')
            await button('Clear filters'); await button('Expand all')
            for kind in ['CSV', 'XLSX', 'PDF']:
                async with page.expect_download() as info: await button('Export ' + kind)
                downloaded = await info.value
                path = Path('/tmp/flexcore-tree-' + engine + '.' + kind.lower()); await downloaded.save_as(path)
                if kind == 'CSV':
                    rows = list(csv.reader(path.open())); assert len(rows) == 12 and rows[0][0] == 'Level'
                elif kind == 'XLSX':
                    sheet = openpyxl.load_workbook(path).active
                    assert sheet.max_row == 12 and isinstance(sheet['D2'].value, (int, float)) and sheet['E2'].is_date
                else:
                    reader = PdfReader(path); assert 'Engineering' in ''.join(p.extract_text() for p in reader.pages)
            passed('CSV/XLSX/PDF export includes all pages and native XLSX numbers/dates')
            await button('Reset tree grid')
            await page.get_by_role('checkbox', name='Fail next lazy load').check()
            remote = page.locator('.fx-treegrid-body [data-node-id="900"]')
            await remote.click(); await page.keyboard.press('ArrowRight')
            await expect(page.locator('#bench-status')).to_contain_text('Simulated load failure')
            await page.keyboard.press('ArrowRight')
            await expect(page.locator('#tree-grid-loads')).to_have_text('Lazy requests: 2')
            await expect(page.locator('.fx-treegrid-body [data-node-id="901"]')).to_be_visible()
            await page.keyboard.press('ArrowLeft'); await page.keyboard.press('ArrowRight')
            await expect(page.locator('#tree-grid-loads')).to_have_text('Lazy requests: 2')
            passed('TreeGrid keyboard expansion retries failed providers and caches children')
            from operations import run_operations
            await run_operations(page, sys.argv[1], passed)
            assert not errors, errors
            await page.screenshot(path='/tmp/flexcore-tree-grid-' + engine + '.png', full_page=True)
            print(f'All {len(checks)} tree browser checks passed ({engine}).', flush=True)
        except:
            await page.screenshot(path='/tmp/flexcore-tree-failure-' + engine + '.png', full_page=True)
            print('Browser errors:', errors, flush=True); raise
        finally: await browser.close()

asyncio.run(main())
